services:
  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3080:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  users_service:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: npm run start:dev
  payment_service:
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - "4222:4222"